name: "GitHub Version Control"
description: "Repo version control on merge via git tags"
author: "Charles Brooker"
runs:
  using: "docker"
  image: "Dockerfile"
outputs:
  new_tag:
    description: "The latest tag after running this action"
  last_tag:
    description: "The latest tag before running this action"
  part:
    description: "The part of version which was bumped"
branding:
  icon: "git-merge"
  color: "purple"
